name: Build Executables

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: win-x64
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish Backend
        shell: bash
        run: |
          dotnet publish Web/Web.csproj \
            -c Release \
            -r ${{ matrix.runtime }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:DebugType=None \
            -p:DebugSymbols=false \
            -o publish/${{ matrix.runtime }}

      - name: Create Linux Startup Script
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          chmod +x publish/${{ matrix.runtime }}/Web
          cp publish/${{ matrix.runtime }}/Web publish/${{ matrix.runtime }}/BlankSpace
          chmod +x publish/${{ matrix.runtime }}/BlankSpace

      - name: Create Windows Startup Script
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          cp publish/${{ matrix.runtime }}/Web.exe publish/${{ matrix.runtime }}/BlankSpace.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlankSpace-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}