name: Build and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        runtime: [ win-x64, linux-x64 ]
        exclude:
          - os: windows-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: win-x64
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish Web/Web.csproj -c Release -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained true -o artifacts

      - name: Add scripts
        shell: bash
        run: |
          cp FRONT/* artifacts/
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            chmod +x artifacts/run.sh
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.runtime }}
          path: artifacts/