name: Build Executables

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            script-ext: sh
          - os: windows-latest
            runtime: win-x64
            script-ext: bat
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish Backend
        run: dotnet publish Web/Web.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true -o publish/${{ matrix.runtime }}

      - name: Prepare FRONT
        run: |
          mkdir -p publish/${{ matrix.runtime }}/FRONT
          cp -r FRONT/* publish/${{ matrix.runtime }}/FRONT/

      - name: Create Startup Script
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo '#!/bin/bash
            ./Web &
            sleep 2
            xdg-open http://localhost:5000/index.html' > publish/${{ matrix.runtime }}/start.sh
            chmod +x publish/${{ matrix.runtime }}/start.sh
          else
            echo '@echo off
            start "" "%~dp0Web.exe"
            timeout /t 2 >nul
            start "" http://localhost:5000/index.html
            exit' > publish/${{ matrix.runtime }}/start.bat
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Executable-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}